secrets:
  external: true
  keys:
    - tac-testnet-use1-env/mainnet/curve/all

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/group.name: tac-mainnet-use1-eks-ext
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-name: tac-mainnet-use1-eks-ext
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: curve.tac.build
      paths:
        - path: /
          pathType: Prefix
          servicePort: http
